version: '3.9'

services:
  # mongoDB services
  mongo_db:
     container_name: db_container
     image: mongo:latest
     restart: always
     ports: 
        - 2717:27017
     volumes: 
        - mongo_db:/data/db
     networks:
        - WORK
  
 

  redis_db:
     container_name: redis_container
     image: redis:latest
     restart: always
     ports:
        - 6379:6379
     volumes:
        - redis_db:/data
     networks:
        - WORK
  


  # api services
  server:
     build: .
     ports: 
        - 3000:3000
     depends_on:
        - mongo_db
     networks:
        - WORK

volumes:
  mongo_db: {}
  redis_db: {}


networks:
  WORK:
  



# // for connecting to docker ==> host.docker.internal (connecting docker server to local host database)

# // for running server + mongoDb database ==> docker  compose up -d 
# // for stoping ==> docker compose down

# // for running server + mongoDb database ==> docker  compose up -d 
# // for stoping ==> docker compose down

#   connecting redis server (on port 6379) to terminal by using command==> docker exec -it 4fa928e667ea bash  
#   and the enter redis-cli to access the shell

#   docker compose  -f docker-compose.yml up  -d  (composing all combined )